const TYPES=['100x150','100x80','100x30'];
const BASE={'100x150':40,'100x80':80,'100x30':10};
const COST_PREFIX='__CUSTO__';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const brl=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const fmt=d=>new Date(d).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'short',timeStyle:'short'});
const monthKey=d=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit'}).format(new Date(d)).slice(0,7);
const monthLabel=k=>{const [y,m]=k.split('-');return new Date(+y,+m-1,1).toLocaleDateString('pt-BR',{month:'long',year:'numeric'})};
const boxes=r=>{const n=Math.max(0,Number(r)||0),c=Math.floor(n/10),x=n%10;return x?`${c} caixa${c===1?'':'s'} + ${x} rolo${x===1?'':'s'}`:`${c} caixa${c===1?'':'s'}`};
const parseMoney=s=>Number(String(s||'').replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,''))||0;
function costMeta(e){if(!String(e.observacao||'').startsWith(COST_PREFIX))return null;try{return JSON.parse(String(e.observacao).slice(COST_PREFIX.length))}catch{return null}}
function plainObs(e){const m=costMeta(e);return m?(m.nota||'—'):(e.observacao||'—')}
function encodeCost({competencia,valor,fornecedor,nota}){return COST_PREFIX+JSON.stringify({competencia,valor:Number(valor)||0,fornecedor:fornecedor||'',nota:nota||''})}
async function api(table,opts={}){const q=new URLSearchParams({table});if(opts.id)q.set('id',opts.id);const r=await fetch('/api/hub-data?'+q.toString(),{method:opts.method||'GET',headers:{'Content-Type':'application/json'},body:opts.body?JSON.stringify(opts.body):undefined});if(!r.ok)throw new Error(await r.text());return r.json()}
function calc(rows,entries){const s={...BASE};entries.forEach(x=>{if(s[x.tamanho]!=null)s[x.tamanho]+=Number(x.rolos||0)});rows.forEach(x=>{if(s[x.tamanho]!=null)s[x.tamanho]-=Number(x.rolos||0)});return s}
function consumption(rows){const m={};rows.forEach(x=>{const k=monthKey(x.created_at);if(!m[k])m[k]={total:0,'100x150':0,'100x80':0,'100x30':0,days:new Set()};const q=Number(x.rolos||0);if(m[k][x.tamanho]!=null)m[k][x.tamanho]+=q;m[k].total+=q;m[k].days.add(new Date(x.created_at).toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'}))});const a=Object.entries(m).sort((a,b)=>a[0].localeCompare(b[0]));return a.map(([k,v],idx)=>{const prev=idx?a[idx-1][1].total:null;return{k,...v,avg:v.days.size?v.total/v.days.size:0,var:prev?((v.total-prev)/prev)*100:null}}).reverse()}
function costStats(entries){const tagged=entries.map(e=>({e,m:costMeta(e)})).filter(x=>x.m&&Number(x.m.valor)>0);const perType={};TYPES.forEach(t=>{const a=tagged.filter(x=>x.e.tamanho===t),value=a.reduce((s,x)=>s+Number(x.m.valor||0),0),rolls=a.reduce((s,x)=>s+Number(x.e.rolos||0),0);perType[t]=rolls?value/rolls:0});const byMonth={};tagged.forEach(x=>{const k=x.m.competencia||monthKey(x.e.created_at);byMonth[k]=(byMonth[k]||0)+Number(x.m.valor||0)});return{tagged,perType,byMonth,total:tagged.reduce((s,x)=>s+Number(x.m.valor||0),0)}}
function table(head,rows){if(!rows.length)return'<div class="muted">Nenhum registro.</div>';return`<div class="table-wrap"><table class="table"><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function header(){return `<header class="top"><div class="wrap"><div class="eyebrow">HUB • CONTROLE OPERACIONAL</div><h1>Painel Administrativo</h1><p class="subtitle">Etiquetas HUB Easy · estoque, consumo, custos e inventário</p><div class="hero-actions"><a class="admin-link" href="/">+ Nova retirada</a></div></div></header>`}
async function load(){document.getElementById('app').innerHTML=`${header()}<main class="admin-shell"><div class="panel">Carregando dados...</div></main>`;try{const [rows,entries,inventories]=await Promise.all([api('retiradas'),api('entradas'),api('inventarios')]);render(rows,entries,inventories)}catch(e){$('.admin-shell').innerHTML=`<div class="panel"><h3>Não foi possível carregar os dados</h3><div class="muted">Atualize a página. Se persistir, o banco de dados está indisponível.</div></div>`}}
function render(rows,entries,inventories){const stock=calc(rows,entries),cons=consumption(rows),cost=costStats(entries),totalStock=TYPES.reduce((s,t)=>s+stock[t],0),currentMonth=monthKey(new Date()),cur=cons.find(x=>x.k===currentMonth),currentConsumption=cur?.total||0,currentSpend=cost.byMonth[currentMonth]||0,estimatedStockCost=TYPES.reduce((s,t)=>s+Math.max(0,stock[t])*cost.perType[t],0),estimatedMonthCost=TYPES.reduce((s,t)=>s+(cur?.[t]||0)*cost.perType[t],0);
$('.admin-shell').innerHTML=`<div class="tabs">${['Resumo','Retiradas','Entrada de estoque','Inventário','Consumo mensal','Controle de custos','Relatórios'].map((x,i)=>`<button class="tab ${i===0?'active':''}" data-tab="t${i}">${x}</button>`).join('')}</div>
<section class="section active" id="t0"><div class="metrics">${TYPES.map(t=>`<div class="metric"><div class="label">Estoque ${t}</div><div class="value">${stock[t]}</div><div class="muted">rolos · ${boxes(stock[t])}</div><span class="status normal">ESTOQUE NORMAL</span></div>`).join('')}<div class="metric"><div class="label">Estoque total</div><div class="value">${totalStock}</div><div class="muted">rolos disponíveis</div></div></div><div class="cost-grid"><div class="cost-card"><span>Consumo no mês</span><strong>${currentConsumption}</strong><small class="muted">rolos retirados</small></div><div class="cost-card"><span>Compras no mês</span><strong>${brl(currentSpend)}</strong><small class="muted">valor registrado</small></div><div class="cost-card"><span>Custo consumo mês</span><strong>${brl(estimatedMonthCost)}</strong><small class="muted">estimado pelo custo médio</small></div><div class="cost-card"><span>Valor do estoque</span><strong>${brl(estimatedStockCost)}</strong><small class="muted">estimado pelo custo médio</small></div></div><div class="two"><div class="panel"><h3>Últimas retiradas</h3>${table(['Data/Hora','Responsável','Tamanho','Rolos'],rows.slice(0,8).map(x=>[fmt(x.created_at),esc(x.responsavel),x.tamanho,x.rolos]))}</div><div class="panel"><h3>Custo médio por rolo</h3>${table(['Etiqueta','Custo médio'],TYPES.map(t=>[t,cost.perType[t]?brl(cost.perType[t]):'—']))}</div></div></section>
<section class="section" id="t1"><div class="panel"><h3>Histórico de retiradas</h3>${table(['Data/Hora','Responsável','Tamanho','Rolos','Ação'],rows.map(x=>[fmt(x.created_at),esc(x.responsavel),x.tamanho,x.rolos,`<button class="btn danger del" data-table="retiradas" data-id="${x.id}">Excluir</button>`]))}</div></section>
<section class="section" id="t2"><div class="two"><div class="panel"><h3>Registrar entrada / compra</h3><div class="form-grid"><div class="field"><label>Tamanho</label><select id="entryType">${TYPES.map(t=>`<option>${t}</option>`).join('')}</select></div><div class="field"><label>Unidade</label><select id="entryUnit"><option value="boxes">Caixas</option><option value="rolls">Rolos</option></select></div><div class="field"><label>Quantidade</label><input id="entryQty" type="number" min="1" value="1"></div><div class="field"><label>Valor total da compra</label><input id="entryValue" placeholder="Ex.: 850,00"></div><div class="field"><label>Competência</label><input id="entryMonth" type="month" value="${currentMonth}"></div><div class="field"><label>Fornecedor</label><input id="entrySupplier"></div><div class="field"><label>Observação</label><textarea id="entryObs"></textarea></div><button class="btn" id="entrySave">Registrar entrada</button></div></div><div class="panel"><h3>Histórico de entradas</h3>${table(['Data','Tamanho','Rolos','Valor','Fornecedor','Observação','Ação'],entries.map(x=>{const m=costMeta(x);return[fmt(x.created_at),x.tamanho,x.rolos,m?brl(m.valor):'—',esc(m?.fornecedor||'—'),esc(plainObs(x)),`<button class="btn danger del" data-table="entradas" data-id="${x.id}">Excluir</button>`]}))}</div></div></section>
<section class="section" id="t3"><div class="two"><div class="panel"><h3>Novo inventário</h3><div class="form-grid"><div class="field"><label>Tipo</label><select id="invType"><option value="quinzenal">Quinzenal</option><option value="mensal">Mensal</option></select></div>${TYPES.map(t=>`<div class="field"><label>Contagem física ${t}</label><input class="inv" data-type="${t}" type="number" min="0" value="${Math.max(0,stock[t])}"></div>`).join('')}<div class="field"><label>Observação</label><textarea id="invObs"></textarea></div><button class="btn" id="invSave">Salvar inventário</button></div></div><div class="panel"><h3>Histórico de inventários</h3>${inventories.length?inventories.map(x=>`<div style="padding:12px 0;border-bottom:1px solid #eee"><strong>${esc(x.tipo)}</strong><div class="muted">${fmt(x.created_at)}</div><button class="btn danger del" data-table="inventarios" data-id="${x.id}">Excluir</button></div>`).join(''):'<div class="muted">Nenhum inventário registrado.</div>'}</div></div></section>
<section class="section" id="t4"><div class="panel"><h3>Consumo mensal de etiquetas</h3>${table(['Mês','100x150','100x80','100x30','Total','Média/dia','Variação'],cons.map(x=>[monthLabel(x.k),x['100x150'],x['100x80'],x['100x30'],x.total,x.avg.toFixed(1),x.var==null?'—':`${x.var>0?'+':''}${x.var.toFixed(1)}%`]))}</div></section>
<section class="section" id="t5"><div class="cost-grid"><div class="cost-card"><span>Total investido</span><strong>${brl(cost.total)}</strong></div><div class="cost-card"><span>Investido no mês</span><strong>${brl(currentSpend)}</strong></div><div class="cost-card"><span>Valor estoque atual</span><strong>${brl(estimatedStockCost)}</strong></div><div class="cost-card"><span>Custo consumo mês</span><strong>${brl(estimatedMonthCost)}</strong></div></div></section>
<section class="section" id="t6"><div class="panel"><h3>Resumo do estoque</h3>${table(['Tamanho','Inicial','Entradas','Retiradas','Saldo','Equivalência'],TYPES.map(t=>[t,BASE[t],entries.filter(x=>x.tamanho===t).reduce((s,x)=>s+Number(x.rolos||0),0),rows.filter(x=>x.tamanho===t).reduce((s,x)=>s+Number(x.rolos||0),0),stock[t],boxes(stock[t])]))}</div></section>`;
bind(stock)}
function bind(stock){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});document.querySelectorAll('.del').forEach(b=>b.onclick=async()=>{if(!confirm('Excluir este registro?'))return;try{await api(b.dataset.table,{method:'DELETE',id:b.dataset.id});load()}catch(e){alert('Não foi possível excluir.')}});if($('#entrySave'))$('#entrySave').onclick=async()=>{const q=Math.max(1,Number($('#entryQty').value||1)),isBoxes=$('#entryUnit').value==='boxes',rolls=isBoxes?q*10:q,value=parseMoney($('#entryValue').value),note=$('#entryObs').value.trim(),obs=value?encodeCost({competencia:$('#entryMonth').value||monthKey(new Date()),valor:value,fornecedor:$('#entrySupplier').value.trim(),nota:note}):(note||null);try{await api('entradas',{method:'POST',body:{tamanho:$('#entryType').value,rolos,caixas:isBoxes?q:null,observacao:obs}});load()}catch(e){alert('Não foi possível registrar a entrada.')}};if($('#invSave'))$('#invSave').onclick=async()=>{const f={};document.querySelectorAll('.inv').forEach(i=>f[i.dataset.type]=Math.max(0,Number(i.value||0)));try{await api('inventarios',{method:'POST',body:{tipo:$('#invType').value,fisico_100x150:f['100x150'],fisico_100x80:f['100x80'],fisico_100x30:f['100x30'],sistema_100x150:stock['100x150'],sistema_100x80:stock['100x80'],sistema_100x30:stock['100x30'],observacao:$('#invObs').value.trim()||null}});load()}catch(e){alert('Não foi possível salvar o inventário.')}}}
load();