import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const supabase=createClient('https://c--102f54f5-5f8b-4f19-aa51-2244c18d2b83-prod.lovable.cloud','sb_publishable_nAJIGfPVHTtEejRo1-TL4g_9uKzid-V');
const TYPES=['100x150','100x80','100x30'];
const BASE={'100x150':40,'100x80':80,'100x30':10};
const LIMITS={'100x150':{low:10,critical:5},'100x80':{low:20,critical:10},'100x30':{low:5,critical:2}};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const brl=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const fmt=d=>new Date(d).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'short',timeStyle:'short'});
const monthKey=d=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit'}).format(new Date(d)).slice(0,7);
const monthLabel=k=>{const [y,m]=k.split('-');return new Date(+y,+m-1,1).toLocaleDateString('pt-BR',{month:'long',year:'numeric'})};
const boxes=r=>{const n=Math.max(0,Number(r)||0),c=Math.floor(n/10),x=n%10;return x?`${c} caixa${c===1?'':'s'} + ${x} rolo${x===1?'':'s'}`:`${c} caixa${c===1?'':'s'}`};
const parseMoney=s=>Number(String(s||'').replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,''))||0;
const COST_PREFIX='__CUSTO__';
function costMeta(e){if(!String(e.observacao||'').startsWith(COST_PREFIX))return null;try{return JSON.parse(String(e.observacao).slice(COST_PREFIX.length))}catch{return null}}
function plainObs(e){const m=costMeta(e);return m?(m.nota||'—'):(e.observacao||'—')}
function encodeCost({competencia,valor,fornecedor,nota}){return COST_PREFIX+JSON.stringify({competencia,valor:Number(valor)||0,fornecedor:fornecedor||'',nota:nota||''})}
function calc(rows,entries){const s={...BASE};entries.forEach(x=>{if(s[x.tamanho]!=null)s[x.tamanho]+=Number(x.rolos||0)});rows.forEach(x=>{if(s[x.tamanho]!=null)s[x.tamanho]-=Number(x.rolos||0)});return s}
function status(t,v){const l=LIMITS[t];if(v<=l.critical)return['critical','ESTOQUE CRÍTICO'];if(v<=l.low)return['low','ESTOQUE BAIXO'];return['normal','ESTOQUE NORMAL']}
function consumption(rows){const m={};rows.forEach(x=>{const k=monthKey(x.created_at);if(!m[k])m[k]={total:0,'100x150':0,'100x80':0,'100x30':0,days:new Set()};const q=Number(x.rolos||0);if(m[k][x.tamanho]!=null)m[k][x.tamanho]+=q;m[k].total+=q;m[k].days.add(new Date(x.created_at).toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'}))});const a=Object.entries(m).sort((a,b)=>a[0].localeCompare(b[0]));return a.map(([k,v],idx)=>{const prev=idx?a[idx-1][1].total:null;return{k,...v,avg:v.days.size?v.total/v.days.size:0,var:prev?((v.total-prev)/prev)*100:null}}).reverse()}
function costStats(entries){const tagged=entries.map(e=>({e,m:costMeta(e)})).filter(x=>x.m&&Number(x.m.valor)>0);const perType={};TYPES.forEach(t=>{const a=tagged.filter(x=>x.e.tamanho===t);const value=a.reduce((s,x)=>s+Number(x.m.valor||0),0),rolls=a.reduce((s,x)=>s+Number(x.e.rolos||0),0);perType[t]=rolls?value/rolls:0});const byMonth={};tagged.forEach(x=>{const k=x.m.competencia||monthKey(x.e.created_at);byMonth[k]=(byMonth[k]||0)+Number(x.m.valor||0)});return{tagged,perType,byMonth,total:tagged.reduce((s,x)=>s+Number(x.m.valor||0),0)}}
function table(head,rows){if(!rows.length)return'<div class="muted">Nenhum registro.</div>';return`<div class="table-wrap"><table class="table"><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function header(){return `<header class="top"><div class="wrap"><div class="eyebrow">HUB • CONTROLE OPERACIONAL</div><h1>Painel Administrativo</h1><p class="subtitle">Etiquetas HUB Easy · estoque, consumo, custos e inventário</p><div class="hero-actions"><a class="admin-link" href="/">+ Nova retirada</a></div></div></header>`}
function invCard(x){return`<div style="padding:14px 0;border-bottom:1px solid #e5e7eb"><strong>Inventário ${esc(x.tipo)}</strong><div class="muted">${fmt(x.created_at)}</div><div class="muted" style="margin-top:7px">100x150: ${x.fisico_100x150} físico / ${x.sistema_100x150} sistema · dif. ${x.fisico_100x150-x.sistema_100x150}<br>100x80: ${x.fisico_100x80} físico / ${x.sistema_100x80} sistema · dif. ${x.fisico_100x80-x.sistema_100x80}<br>100x30: ${x.fisico_100x30} físico / ${x.sistema_100x30} sistema · dif. ${x.fisico_100x30-x.sistema_100x30}</div>${x.observacao?`<div class="muted">Obs.: ${esc(x.observacao)}</div>`:''}<button class="btn danger del" style="margin-top:9px" data-table="inventarios" data-id="${x.id}">Excluir</button></div>`}
async function admin(){
 $('#app').innerHTML=`${header()}<main class="admin-shell"><div class="panel">Carregando dados...</div></main>`;
 const [r,e,i]=await Promise.all([supabase.from('retiradas').select('*').order('created_at',{ascending:false}),supabase.from('entradas').select('*').order('created_at',{ascending:false}),supabase.from('inventarios').select('*').order('created_at',{ascending:false})]);
 if(r.error||e.error||i.error){$('.admin-shell').innerHTML='<div class="panel">Não foi possível carregar o painel.</div>';return}
 render(r.data||[],e.data||[],i.data||[]);
}
function render(rows,entries,inventories){
 const stock=calc(rows,entries),cons=consumption(rows),cost=costStats(entries),totalStock=TYPES.reduce((s,t)=>s+stock[t],0),totalUsed=rows.reduce((s,x)=>s+Number(x.rolos||0),0),alerts=TYPES.filter(t=>status(t,stock[t])[0]!=='normal');
 const currentMonth=monthKey(new Date()),cur=cons.find(x=>x.k===currentMonth),currentConsumption=cur?.total||0,currentSpend=cost.byMonth[currentMonth]||0;
 const estimatedStockCost=TYPES.reduce((s,t)=>s+Math.max(0,stock[t])*cost.perType[t],0);
 const estimatedMonthCost=TYPES.reduce((s,t)=>s+(cur?.[t]||0)*cost.perType[t],0);
 $('.admin-shell').innerHTML=`
 <style>.cost-good{color:#0f766e;font-weight:900}.cost-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:16px 0}.cost-card{background:#fff;border:1px solid #e5e7eb;border-radius:17px;padding:18px}.cost-card span{font-size:11px;color:#667085;font-weight:900;text-transform:uppercase;letter-spacing:.07em}.cost-card strong{display:block;font-size:27px;color:#17365d;margin:7px 0}.note{background:#f7f9fc;border:1px solid #e5e7eb;border-radius:13px;padding:12px 14px;color:#667085;font-size:12px;margin-top:12px}@media(max-width:850px){.cost-grid{grid-template-columns:1fr 1fr}}@media(max-width:520px){.cost-grid{grid-template-columns:1fr}}</style>
 <div class="tabs">${['Resumo','Retiradas','Entrada de estoque','Inventário','Consumo mensal','Controle de custos','Relatórios'].map((x,i)=>`<button class="tab ${i===0?'active':''}" data-tab="t${i}">${x}</button>`).join('')}</div>
 <section class="section active" id="t0">${alerts.length?`<div class="alert"><strong>⚠ Atenção ao estoque</strong><div class="muted" style="margin-top:6px">${alerts.map(t=>`Etiqueta ${t}: ${stock[t]} rolos restantes (${status(t,stock[t])[1]}).`).join('<br>')}</div></div>`:''}
 <div class="metrics">${TYPES.map(t=>{const st=status(t,stock[t]);return`<div class="metric"><div class="label">Estoque ${t}</div><div class="value">${stock[t]}</div><div class="muted">rolos · ${boxes(stock[t])}</div><span class="status ${st[0]}">${st[1]}</span></div>`}).join('')}<div class="metric"><div class="label">Estoque total</div><div class="value">${totalStock}</div><div class="muted">rolos disponíveis</div></div></div>
 <div class="cost-grid"><div class="cost-card"><span>Consumo no mês</span><strong>${currentConsumption}</strong><small class="muted">rolos retirados</small></div><div class="cost-card"><span>Compras no mês</span><strong>${brl(currentSpend)}</strong><small class="muted">valor registrado</small></div><div class="cost-card"><span>Custo consumo mês</span><strong>${brl(estimatedMonthCost)}</strong><small class="muted">estimado pelo custo médio</small></div><div class="cost-card"><span>Valor do estoque</span><strong>${brl(estimatedStockCost)}</strong><small class="muted">estimado pelo custo médio</small></div></div>
 <div class="two"><div class="panel"><h3>Últimas retiradas</h3>${table(['Data/Hora','Responsável','Tamanho','Rolos'],rows.slice(0,8).map(x=>[fmt(x.created_at),esc(x.responsavel),x.tamanho,x.rolos]))}</div><div class="panel"><h3>Custo médio por rolo</h3>${table(['Etiqueta','Custo médio'],TYPES.map(t=>[t,cost.perType[t]?`<span class="cost-good">${brl(cost.perType[t])}</span>`:'—']))}</div></div></section>
 <section class="section" id="t1"><div class="panel"><h3>Histórico de retiradas</h3>${table(['Data/Hora','Responsável','Tamanho','Rolos','Ação'],rows.map(x=>[fmt(x.created_at),esc(x.responsavel),x.tamanho,x.rolos,`<button class="btn danger del" data-table="retiradas" data-id="${x.id}">Excluir</button>`]))}</div></section>
 <section class="section" id="t2"><div class="two"><div class="panel"><h3>Registrar entrada / compra</h3><div class="form-grid"><div class="field"><label>Tamanho</label><select id="entryType">${TYPES.map(t=>`<option>${t}</option>`).join('')}</select></div><div class="field"><label>Unidade</label><select id="entryUnit"><option value="boxes">Caixas</option><option value="rolls">Rolos</option></select></div><div class="field"><label>Quantidade</label><input id="entryQty" type="number" min="1" value="1"></div><div class="field"><label>Valor total da compra (opcional)</label><input id="entryValue" inputmode="decimal" placeholder="Ex.: 850,00"></div><div class="field"><label>Competência</label><input id="entryMonth" type="month" value="${currentMonth}"></div><div class="field"><label>Fornecedor (opcional)</label><input id="entrySupplier" placeholder="Nome do fornecedor"></div><div class="field"><label>Observação</label><textarea id="entryObs" placeholder="Opcional"></textarea></div><div class="muted" id="entryPreview">Será somado: 10 rolos</div><button class="btn" id="entrySave">Registrar entrada</button></div><div class="note">Ao informar um valor, a entrada também passa a compor o Controle de Custos. Se deixar o valor vazio, será apenas uma entrada de estoque.</div></div><div class="panel"><h3>Histórico de entradas</h3>${table(['Data','Tamanho','Rolos','Valor','Fornecedor','Observação','Ação'],entries.map(x=>{const m=costMeta(x);return[fmt(x.created_at),x.tamanho,x.rolos,m?brl(m.valor):'—',esc(m?.fornecedor||'—'),esc(plainObs(x)),`<button class="btn danger del" data-table="entradas" data-id="${x.id}">Excluir</button>`]}))}</div></div></section>
 <section class="section" id="t3"><div class="two"><div class="panel"><h3>Novo inventário</h3><div class="form-grid"><div class="field"><label>Tipo</label><select id="invType"><option value="quinzenal">Quinzenal</option><option value="mensal">Mensal</option></select></div>${TYPES.map(t=>`<div class="field"><label>Contagem física ${t} (rolos)</label><input class="inv" data-type="${t}" type="number" min="0" value="${Math.max(0,stock[t])}"><div class="muted">Sistema: ${stock[t]} rolos</div></div>`).join('')}<div class="field"><label>Observação</label><textarea id="invObs"></textarea></div><button class="btn" id="invSave">Salvar inventário</button></div></div><div class="panel"><h3>Histórico de inventários</h3>${inventories.length?inventories.map(invCard).join(''):'<div class="muted">Nenhum inventário registrado.</div>'}</div></div></section>
 <section class="section" id="t4"><div class="panel"><h3>Consumo mensal de etiquetas</h3><p class="muted">Calculado automaticamente pelas retiradas registradas.</p>${table(['Mês','100x150','100x80','100x30','Total','Média/dia','Variação','Custo estimado'],cons.map(x=>[monthLabel(x.k),x['100x150'],x['100x80'],x['100x30'],`<b>${x.total}</b>`,x.avg.toFixed(1),x.var==null?'—':`${x.var>0?'+':''}${x.var.toFixed(1)}%`,brl(TYPES.reduce((s,t)=>s+x[t]*cost.perType[t],0))]))}</div></section>
 <section class="section" id="t5"><div class="cost-grid"><div class="cost-card"><span>Total investido</span><strong>${brl(cost.total)}</strong><small class="muted">compras com custo informado</small></div><div class="cost-card"><span>Investido no mês</span><strong>${brl(currentSpend)}</strong><small class="muted">${monthLabel(currentMonth)}</small></div><div class="cost-card"><span>Valor estoque atual</span><strong>${brl(estimatedStockCost)}</strong><small class="muted">estimativa</small></div><div class="cost-card"><span>Custo consumo mês</span><strong>${brl(estimatedMonthCost)}</strong><small class="muted">estimativa</small></div></div><div class="panel"><h3>Compras por mês</h3>${table(['Mês','Valor investido'],Object.entries(cost.byMonth).sort((a,b)=>b[0].localeCompare(a[0])).map(([k,v])=>[monthLabel(k),`<b>${brl(v)}</b>`]))}</div><div class="panel" style="margin-top:16px"><h3>Compras registradas</h3>${table(['Competência','Data','Etiqueta','Rolos','Caixas','Valor','Custo/rolo','Fornecedor'],cost.tagged.map(({e,m})=>[monthLabel(m.competencia||monthKey(e.created_at)),fmt(e.created_at),e.tamanho,e.rolos,e.caixas??'—',brl(m.valor),brl(Number(m.valor)/Math.max(1,Number(e.rolos))),esc(m.fornecedor||'—')]))}</div></section>
 <section class="section" id="t6"><div class="panel"><h3>Resumo do estoque</h3>${table(['Tamanho','Inicial','Entradas','Retiradas','Saldo','Equivalência','Custo médio/rolo','Valor estimado saldo'],TYPES.map(t=>[t,BASE[t],entries.filter(x=>x.tamanho===t).reduce((s,x)=>s+Number(x.rolos||0),0),rows.filter(x=>x.tamanho===t).reduce((s,x)=>s+Number(x.rolos||0),0),stock[t],boxes(stock[t]),cost.perType[t]?brl(cost.perType[t]):'—',cost.perType[t]?brl(Math.max(0,stock[t])*cost.perType[t]):'—']))}</div><div class="panel" style="margin-top:16px"><h3>Indicadores gerais</h3><div class="three"><div class="metric"><div class="label">Rolos retirados</div><div class="value">${totalUsed}</div></div><div class="metric"><div class="label">Registros de retirada</div><div class="value">${rows.length}</div></div><div class="metric"><div class="label">Rolos recebidos</div><div class="value">${entries.reduce((s,x)=>s+Number(x.rolos||0),0)}</div></div></div></div></section>`;
 bind(stock);
}
function bind(stock){
 document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
 document.querySelectorAll('.del').forEach(b=>b.onclick=async()=>{if(!confirm('Excluir este registro?'))return;const {error}=await supabase.from(b.dataset.table).delete().eq('id',b.dataset.id);if(error)return alert('Não foi possível excluir.');admin()});
 const preview=()=>{if(!$('#entryQty'))return;const q=Math.max(1,Number($('#entryQty').value||1)),rolls=$('#entryUnit').value==='boxes'?q*10:q,val=parseMoney($('#entryValue').value);$('#entryPreview').textContent=`Será somado: ${rolls} rolos${val?` · custo médio desta entrada: ${brl(val/rolls)} por rolo`:''}`};
 if($('#entryQty')){['entryQty','entryUnit','entryValue'].forEach(id=>$('#'+id).addEventListener(id==='entryUnit'?'change':'input',preview));$('#entrySave').onclick=async()=>{const q=Math.max(1,Number($('#entryQty').value||1)),isBoxes=$('#entryUnit').value==='boxes',rolls=isBoxes?q*10:q,value=parseMoney($('#entryValue').value),note=$('#entryObs').value.trim();const obs=value?encodeCost({competencia:$('#entryMonth').value||monthKey(new Date()),valor:value,fornecedor:$('#entrySupplier').value.trim(),nota:note}):(note||null);const {error}=await supabase.from('entradas').insert({tamanho:$('#entryType').value,rolos:rolls,caixas:isBoxes?q:null,observacao:obs});if(error)return alert('Não foi possível registrar a entrada.');alert('Entrada registrada com sucesso.');admin()}};
 if($('#invSave'))$('#invSave').onclick=async()=>{const f={};document.querySelectorAll('.inv').forEach(i=>f[i.dataset.type]=Math.max(0,Number(i.value||0)));const payload={tipo:$('#invType').value,fisico_100x150:f['100x150'],fisico_100x80:f['100x80'],fisico_100x30:f['100x30'],sistema_100x150:stock['100x150'],sistema_100x80:stock['100x80'],sistema_100x30:stock['100x30'],observacao:$('#invObs').value.trim()||null};const {error}=await supabase.from('inventarios').insert(payload);if(error)return alert('Não foi possível salvar o inventário.');alert('Inventário salvo. O estoque não foi alterado.');admin()};
}
admin();