// Previsão de estoque e compras — Etiquetas HUB
(function(){if(!location.pathname.startsWith('/admin'))return;
const css=document.createElement('style');css.textContent=`
.forecast-wrap{margin:16px 0;background:#fff;border:1px solid #d8e1e4;border-radius:14px;padding:24px;box-shadow:0 8px 24px rgba(38,56,64,.05)}
.forecast-head{margin:0 0 22px 0}.forecast-head h2{margin:0;color:#18262d;font-size:18px;font-weight:800}.forecast-head p{margin:7px 0 0;color:#61757d;font-size:13px}
.forecast-scroll{overflow-x:auto}.forecast-table{width:100%;border-collapse:collapse;min-width:1050px}.forecast-table th{padding:14px 16px;text-align:left;background:#f5f7f7;border-top:1px solid #d7e0e2;border-bottom:1px solid #d7e0e2;color:#52646d;font-size:10px;letter-spacing:1.15px;text-transform:uppercase;line-height:1.35}.forecast-table td{padding:18px 16px;border-bottom:1px solid #d7e0e2;color:#17242b;font-size:13px;vertical-align:middle}.forecast-table tbody tr:last-child td{border-bottom:0}.forecast-item{font-weight:800}.forecast-status{display:inline-block;padding:5px 12px;border-radius:999px;font-size:11px;font-weight:800;white-space:nowrap}.forecast-status.normal{background:#e9f8f1;color:#087b50;border:1px solid #ccebdd}.forecast-status.atencao{background:#fff8e7;color:#b56b00;border:1px solid #eadfbd}.forecast-status.comprar{background:#fff0f0;color:#d61f1f;border:1px solid #ebd2d2}@media(max-width:700px){.forecast-wrap{padding:16px}.forecast-head h2{font-size:17px}}
`;document.head.appendChild(css);
const dateBR=d=>d?d.toLocaleDateString('pt-BR'):'—',add=n=>{if(!Number.isFinite(n))return null;const d=new Date();d.setDate(d.getDate()+Math.max(0,Math.floor(n)));return d};
async function build(){const sec=document.querySelector('#relatorios');if(!sec||sec.querySelector('.forecast-wrap'))return;try{
const api=async table=>{const r=await fetch('/api/hub-data?table='+table);if(!r.ok)throw 0;return r.json()};
const [rows,entries,inventories]=await Promise.all([api('retiradas'),api('entradas'),api('inventarios')]);
const types=['100x150','100x80','100x30'],base={'100x150':40,'100x80':80,'100x30':10},latest=inventories[0]||null,inventoryAt=latest?new Date(latest.created_at).getTime():null;
const stock=latest?{'100x150':Number(latest.fisico_100x150||0),'100x80':Number(latest.fisico_100x80||0),'100x30':Number(latest.fisico_100x30||0)}:{...base};
entries.forEach(x=>stock[x.tamanho]!=null&&(!inventoryAt||new Date(x.created_at).getTime()>inventoryAt)&&(stock[x.tamanho]+=Number(x.rolos)||0));
rows.forEach(x=>stock[x.tamanho]!=null&&(!inventoryAt||new Date(x.created_at).getTime()>inventoryAt)&&(stock[x.tamanho]-=Number(x.rolos)||0));
const now=new Date(),c30=new Date(now-30*864e5),c7=new Date(now-7*864e5);
const body=types.map(t=>{const q30=rows.filter(x=>x.tamanho===t&&new Date(x.created_at)>=c30).reduce((s,x)=>s+(Number(x.rolos)||0),0),q7=rows.filter(x=>x.tamanho===t&&new Date(x.created_at)>=c7).reduce((s,x)=>s+(Number(x.rolos)||0),0),avg=q30/30,avg7=q7/7,days=avg>0?stock[t]/avg:Infinity,min=Math.ceil(avg*14),buy=Math.max(0,Math.ceil(avg*60-stock[t])),trend=avg>0?((avg7-avg)/avg)*100:0,order=avg>0?Math.max(0,(stock[t]-min)/avg):Infinity,status=days<=14?'comprar':days<=30?'atencao':'normal',label=days<=14?'Comprar':days<=30?'Atenção':'Normal';return `<tr><td class="forecast-item">Etiqueta ${t}</td><td>${Math.max(0,Math.round(stock[t]))}</td><td>${min}</td><td>${Number.isFinite(days)?Math.max(0,Math.floor(days))+' dias':'—'}</td><td>${avg.toFixed(1)}</td><td>${trend>=0?'+':''}${trend.toFixed(0)}%</td><td>${dateBR(add(days))}</td><td>${dateBR(add(order))}</td><td>${buy}</td><td><span class="forecast-status ${status}">${label}</span></td></tr>`}).join('');
const el=document.createElement('div');el.className='forecast-wrap';el.innerHTML=`<div class="forecast-head"><h2>Previsão de estoque e compras</h2><p>Estimativas baseadas no consumo dos últimos 30 dias e segurança de 14 dias.</p></div><div class="forecast-scroll"><table class="forecast-table"><thead><tr><th>Item</th><th>Estoque</th><th>Mínimo</th><th>Cobertura</th><th>Média/dia</th><th>Tendência<br>7d</th><th>Ruptura<br>estimada</th><th>Compra<br>sugerida</th><th>Qtd.<br>sugerida</th><th>Status</th></tr></thead><tbody>${body}</tbody></table></div>`;
const anchor=sec.querySelector('.panel');if(anchor)anchor.after(el);else sec.appendChild(el)
}catch(e){}}
new MutationObserver(()=>build()).observe(document.getElementById('app'),{childList:true,subtree:true});setTimeout(build,600);
})();